SkulManagementSchool/SkulManagementSchool/Models/LearnersAssessment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SkulManagementSchool.Models
{
    public class LearnersAssessment
    {
        [Key]
        public int LearnersAssessmentId { get; set; }
        [Display(Name = "Mark")]
        public int Mark { get; set; }
        [Display(Name = "Assessment")]
        [ForeignKey("Assessment")]
        public int AssessmentId { get; set; }
        [ForeignKey("Learner")]
        public int LearnerId { get; set; }
        public virtual Learner Learner { get; set; }
        public virtual Assessment Assessment { get; set; }
    }
}

SkulManagementSchool/SkulManagementSchool/Controllers/LearnersAssessmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SkulManagementSchool.Models;

namespace SkulManagementSchool.Controllers
{
    public class LearnersAssessmentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: LearnersAssessments
        public ActionResult Index()
        {
            var learnersAssessments = db.LearnersAssessments.Include(l => l.Assessment).Include(l => l.Learner);
            return View(learnersAssessments.ToList());
        }

        public ActionResult MarksCaptured(int assessmentId, string className,string subjectName)
        {
            ViewBag.ClassName = className;
            ViewBag.SubjectName = subjectName;
            var learnersAssessments = db.LearnersAssessments.Include(l => l.Assessment).Include(l => l.Learner).Where(l=>l.AssessmentId==assessmentId);
            ViewBag.AssessmentName = learnersAssessments.FirstOrDefault().Assessment.AssessmentName;

            return View(learnersAssessments.ToList());
        }

        // GET: LearnersAssessments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LearnersAssessment learnersAssessment = db.LearnersAssessments.Find(id);
            if (learnersAssessment == null)
            {
                return HttpNotFound();
            }
            return View(learnersAssessment);
        }

        // GET: LearnersAssessments/Create
        public ActionResult Create()
        {
            ViewBag.AssessmentId = new SelectList(db.Assessments, "AssessmentId", "AssessmentName");
            ViewBag.LearnerId = new SelectList(db.Learners, "LearnerId", "LearnerName");
            return View();
        }

        public ActionResult CaptureMarks(int assessmentId,int classroomId)
        {
            var classList = db.Learners.Where(p => p.ClassroomId == classroomId).ToList();
            var learnerMarksList = new List<LearnersAssessment>();

            foreach(var item in classList)
            {
                var la = new LearnersAssessment();
                la.AssessmentId = assessmentId;
                la.Learner = item;
                la.LearnerId = item.LearnerId;
                la.Mark = 0;
                learnerMarksList.Add(la);
            }
            return View(learnerMarksList);
        }

        [HttpPost]
        public ActionResult CaptureMarks(List<LearnersAssessment> learnersAssessments)
        {
            foreach(var item in learnersAssessments)
            {
                var tot = db.Assessments.Where(k => k.AssessmentId == item.AssessmentId).Select(l => l.TotalMarkAssessment).FirstOrDefault();
                var learner = db.Learners.Where(n => n.LearnerId == item.LearnerId).FirstOrDefault();
                if (item.Mark > tot)
                {
                    item.Learner = learner;
                    ModelState.AddModelError("", "Unable to save Marks Cannot Be greater " + tot + " Check " + learner.LearnerName + "'s Mark");
                    return View(learnersAssessments);
                }
            }

            foreach (var item in learnersAssessments)
            {
                var learnerAssessment = db.LearnersAssessments.Where(p => p.AssessmentId == item.AssessmentId && p.LearnerId == item.LearnerId).FirstOrDefault();
                if (learnerAssessment != null)
                {
                    learnerAssessment.Mark = item.Mark;
                    db.Entry(learnerAssessment).State = EntityState.Modified;
                }
                else
                {
                    db.LearnersAssessments.Add(item);
                }

                db.SaveChanges();
            }
            var assessmentId = learnersAssessments.FirstOrDefault().AssessmentId;
            var subjectId = db.Assessments.Where(l => l.AssessmentId == assessmentId).Select(p => p.SubjectId).FirstOrDefault();

            return RedirectToAction("SubjectIndex","Assessments",new { subjectId=subjectId});
        }

        // POST: LearnersAssessments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LearnersAssessmentId,Mark,AssessmentId,LearnerId")] LearnersAssessment learnersAssessment)
        {
            if (ModelState.IsValid)
            {
                db.LearnersAssessments.Add(learnersAssessment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AssessmentId = new SelectList(db.Assessments, "AssessmentId", "AssessmentName", learnersAssessment.AssessmentId);
            ViewBag.LearnerId = new SelectList(db.Learners, "LearnerId", "LearnerName", learnersAssessment.LearnerId);
            return View(learnersAssessment);
        }

        // GET: LearnersAssessments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LearnersAssessment learnersAssessment = db.LearnersAssessments.Find(id);
            if (learnersAssessment == null)
            {
                return HttpNotFound();
            }
            ViewBag.AssessmentId = new SelectList(db.Assessments, "AssessmentId", "AssessmentName", learnersAssessment.AssessmentId);
            ViewBag.LearnerId = new SelectList(db.Learners, "LearnerId", "LearnerName", learnersAssessment.LearnerId);
            return View(learnersAssessment);
        }

        // POST: LearnersAssessments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LearnersAssessmentId,Mark,AssessmentId,LearnerId")] LearnersAssessment learnersAssessment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(learnersAssessment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AssessmentId = new SelectList(db.Assessments, "AssessmentId", "AssessmentName", learnersAssessment.AssessmentId);
            ViewBag.LearnerId = new SelectList(db.Learners, "LearnerId", "LearnerName", learnersAssessment.LearnerId);
            return View(learnersAssessment);
        }

        // GET: LearnersAssessments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LearnersAssessment learnersAssessment = db.LearnersAssessments.Find(id);
            if (learnersAssessment == null)
            {
                return HttpNotFound();
            }
            return View(learnersAssessment);
        }

        // POST: LearnersAssessments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LearnersAssessment learnersAssessment = db.LearnersAssessments.Find(id);
            db.LearnersAssessments.Remove(learnersAssessment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SkulManagementSchool/SkulManagementSchool/Views/LearnersAssessments/CaptureMarks.cshtml
@model List<SkulManagementSchool.Models.LearnersAssessment>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Capture Marks</title>
</head>
<body>


    @using (Html.BeginForm("CaptureMarks", "LearnersAssessments", FormMethod.Post))
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayName("Learner Name")
                </th>
                <th>
                    @Html.DisplayName("Mark")
                </th>
                <th></th>
            </tr>

            @for (int i = 0; i < Model.Count(); i++)
            {
                @Html.HiddenFor(modelItem => modelItem[i].Learner)
                @Html.HiddenFor(modelItem => modelItem[i].LearnerId)
                @Html.HiddenFor(modelItem => modelItem[i].AssessmentId)
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem[i].Learner.LearnerName)
                    </td>

                    <td>
                        @Html.EditorFor(modelItem => modelItem[i].Mark)
                    </td>
                </tr>
            }

        </table>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit Marks" class="btn btn-default" />
            </div>
        </div>
    }
</body>
</html>

SkulManagementSchool/SkulManagementSchool/Views/LearnersAssessments/Create.cshtml
@model SkulManagementSchool.Models.LearnersAssessment

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Capture Marks</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Mark, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Mark, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Mark, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.AssessmentId, "Assessment", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("AssessmentId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AssessmentId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.LearnerId, "Learner", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("LearnerId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LearnerId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

SkulManagementSchool/SkulManagementSchool/Views/LearnersAssessments/Delete.cshtml
@model SkulManagementSchool.Models.LearnersAssessment

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>LearnersAssessment</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Assessment.AssessmentName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Assessment.AssessmentName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Learner.LearnerName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Learner.LearnerName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Mark)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Mark)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

SkulManagementSchool/SkulManagementSchool/Views/LearnersAssessments/Details.cshtml
@model SkulManagementSchool.Models.LearnersAssessment

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>LearnersAssessment</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Assessment.AssessmentName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Assessment.AssessmentName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Learner.LearnerName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Learner.LearnerName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Mark)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Mark)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.LearnersAssessmentId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

SkulManagementSchool/SkulManagementSchool/Views/LearnersAssessments/Edit.cshtml
@model SkulManagementSchool.Models.LearnersAssessment

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>LearnersAssessment</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.LearnersAssessmentId)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Mark, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Mark, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Mark, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.AssessmentId, "AssessmentId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("AssessmentId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AssessmentId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.LearnerId, "LearnerId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("LearnerId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LearnerId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

SkulManagementSchool/SkulManagementSchool/Views/LearnersAssessments/Index.cshtml
@model IEnumerable<SkulManagementSchool.Models.LearnersAssessment>



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Assessment.AssessmentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Learner.LearnerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mark)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Assessment.AssessmentName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Learner.LearnerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mark)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.LearnersAssessmentId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.LearnersAssessmentId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.LearnersAssessmentId })
                </td>
            </tr>
        }

    </table>
</body>
</html>

SkulManagementSchool/SkulManagementSchool/Views/LearnersAssessments/MarksCaptured.cshtml
@model IEnumerable<SkulManagementSchool.Models.LearnersAssessment>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="card-header card-header-primary">
        <h4 class="card-title ">
            <i></i>@ViewBag.ClassName /
            <i></i>@ViewBag.SubjectName /
            <i></i>Assessments/
            <i></i>@ViewBag.AssessmentName
        </h4>
    </div>
    <table class="table">
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Learner.LearnerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mark)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Learner.LearnerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mark)
                </td>
            </tr>
        }

    </table>
</body>
</html>