SkulManagementSchool/SkulManagementSchool/Controllers/GradesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SkulManagementSchool.Models;

namespace SkulManagementSchool.Controllers
{
    public class GradesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Grades
        public ActionResult Index()
        {
            return View(db.Grades.ToList());
        }

        // GET: Grades/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grade grade = db.Grades.Find(id);
            if (grade == null)
            {
                return HttpNotFound();
            }
            return View(grade);
        }

        // GET: Grades/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Grades/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GradeId,GradeName")] Grade grade)
        {
            if (ModelState.IsValid)
            {
                db.Grades.Add(grade);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(grade);
        }

        // GET: Grades/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grade grade = db.Grades.Find(id);
            if (grade == null)
            {
                return HttpNotFound();
            }
            return View(grade);
        }

        // POST: Grades/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GradeId,GradeName")] Grade grade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(grade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(grade);
        }

        // GET: Grades/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grade grade = db.Grades.Find(id);
            if (grade == null)
            {
                return HttpNotFound();
            }
            return View(grade);
        }

        // POST: Grades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Grade grade = db.Grades.Find(id);
            db.Grades.Remove(grade);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SkulManagementSchool/SkulManagementSchool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  
    <head>
        <meta charset="utf-8">
        <title>Skill Best Education </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="" />
        <meta name="author" content="http://webthemez.com" />
        <!-- css -->
        <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/Content/css/fancybox/jquery.fancybox.css" rel="stylesheet">
        <link href="~/Content/css/jcarousel.css" rel="stylesheet" />
        <link href="~/Content/css/flexslider.css" rel="stylesheet" />
        <link href="~/Content/js/owl-carousel/owl.carousel.css" rel="stylesheet">
        <link href="~/Content/css/style.css" rel="stylesheet" />

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
              <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
            <![endif]-->
    </head>
    <body>
        <div id="wrapper2" class="home-page">
            <div class="topbar">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <p class="pull-left hidden-xs">School Management System</p>
                            <p class="pull-right"><i class="fa fa-phone"></i>Tel No. (031) 258-3471</p>
                        </div>


                    </div>
                </div>
            </div>
            <!-- start header -->
            <header>
                <div id="wrapper"  class="navbar navbar-default"  navbar-static-top">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="@Url.Action("Index","Home")"><img src="~/Content/img/logo.png" alt="logo" /></a>
                        </div>
                        <div class="navbar-collapse collapse ">
                            <ul class="nav navbar-nav">
                                <li class="active"><a href="@Url.Action("Index","Home")">Home</a></li>
                                <li class="dropdown">
                                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">About Us <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">Our School</a></li>
                                        <li><a href="#">Our Team</a></li>
                                        <li><a href="#">News</a></li>
                                        <li><a href="#">Investors</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">Learner Profile <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        @if (User.IsInRole("Parent"))
                                        {
                                            <li><a href="@Url.Action("AddLearner", "Learners")">Add New Learner</a></li>
                                        }
                                            <li><a href="@Url.Action("Index","Learners")">Registered Learners</a></li>

                                        </ul>
                                </li>
                                @if (User.IsInRole("admin"))
                                {
                                    <li class="dropdown">
                                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Marks <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="@Url.Action("Index", "Subjects")">Subjects</a></li>
                                            <li><a href="@Url.Action("Index", "Assessments")">Assessments</a></li>
                                            <li><a href="@Url.Action("Index", "LearnersAssessments")">LearnersAssessments</a></li>
                                           
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Classroom <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="@Url.Action("Index", "Classrooms")">Classrooms</a></li>
                                            <li><a href="@Url.Action("Index", "Grades")">Grades</a></li>

                                        </ul>
                                    </li>
                                }

                                    @if (Request.IsAuthenticated)
                                    {
                                        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                                        {
                                            @Html.AntiForgeryToken()

                                            <ul class="nav navbar-nav navbar-right">
                                                <li>
                                                    <a>Hello @ViewBag.ParentName!</a>
                                                </li>
                                                <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                                            </ul>
                                        }
                                    }
                                    else
                                    {
                                        <ul class="nav navbar-nav navbar-right">
                                            <li class="active"><a href="/account/register">Apply Online</a></li>

                                            <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                                        </ul>
                                    }
                                </ul>

                        </div>
                    </div>
                </div>

            </header>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
        </div>
        <!-- javascript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="~/Content/js/jquery.js"></script>
        <script src="~/Content/js/jquery.easing.1.3.js"></script>
        <script src="~/Content/js/bootstrap.min.js"></script>
        <script src="~/Content/js/jquery.fancybox.pack.js"></script>
        <script src="~/Content/js/jquery.fancybox-media.js"></script>
        <script src="~/Content/js/jquery.flexslider.js"></script>
        <script src="~/Content/js/animate.js"></script>
        <!-- Vendor Scripts -->
        <script src="~/Content/js/modernizr.custom.js"></script>
        <script src="~/Content/js/jquery.isotope.min.js"></script>
        <script src="~/Content/js/jquery.magnific-popup.min.js"></script>
        <script src="~/Content/js/animate.js"></script>
        <script src="~/Content/js/custom.js"></script>
        <script src="~/Content/js/owl-carousel/owl.carousel.js"></script>
    </body>
</html>